name: Auto merge
on:
  pull_request:
permissions:
  contents: write
  checks: read
  pull-requests: write
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@38cd6ebc01e8b5b14ac9a90a5579d04b02e79099 # pinned to latest
    with:
      azure_cloud: true
      tfchecks_azure: '["tf-lint / tflint"]'
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
