name: Auto merge
on:
  pull_request:
permissions:
  contents: write
  checks: read
  pull-requests: write
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@d27d2d3b49bcf14db85bdfb0f57956abf18bb091 # pinned to latest
    with:
      azure_cloud: true
      tfchecks_azure: '["tf-lint / tflint"]'
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
